[package]
name = "baddie-csprng"
version = "1.0.0"
edition = "2024"
description = "A keyed CSPRNG backed by the BLAKE3 cryptographic hash function."
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://git.colorized.life/baddie-csprng"
keywords = ["no_std", "prng", "random", "blake3", "xof"]
categories = ["cryptography"]
exclude = ["/scripts", "/.gitignore"]

[features]
default = []

[dependencies]
blake3 = { version = "1.8.5", default-features = false }

[profile.dev.package."*"]
opt-level = 1
debug = false

[profile.release]
lto = true
codegen-units = 1
strip = true
